### PR TITLE
task-2

### PR DESCRIPTION
**Pull request by luckydevil13**

### CODE REVIEW

**Comment by ReshetovItsMe** [comment]
reviewed ✅

**Comment by AndreyAusianik** [comment]
hi, I believe https://dnt9xyt7ssggy.cloudfront.net/cart should open cart page, not NoSuchKey error. Could you please fix it?

**Comment by luckydevil13** [comment]
> hi, I believe https://dnt9xyt7ssggy.cloudfront.net/cart should open cart page, not NoSuchKey error. Could you please fix it?

try to open https://dnt9xyt7ssggy.cloudfront.net/ first and that navigate to cart
It's routing by angular

**Comment by AndreyAusianik** [comment]
that is it. angular routing works, but user should be able to land on /cart page from the very beginning. you should tune your error handling configuration

**Comment by luckydevil13** [comment]
> that is it. angular routing works, but user should be able to land on /cart page from the very beginning. you should tune your error handling configuration

show me requeriments please how /cart should works.
PS: out of course scope

**Comment by AndreyAusianik** [comment]
look, on any site that is SPA and being served somewhere you can navigate to any /path/subpath directly. it is not normal for user to first enter the `/` page, then navigate with a lot of click to where he wants

**Comment by AndreyAusianik** [comment]
btw error is in aws configuration, not in the angular routing

**Comment by luckydevil13** [comment]
> look, on any site that is SPA and being served somewhere you can navigate to any /path/subpath directly. it is not normal for user to first enter the `/` page, then navigate with a lot of click to where he wants

depends on requerments. 
this angular shop fork don't save cart 

> btw error is in aws configuration, not in the angular routing

ok, do you know root cause?

**Comment by AndreyAusianik** [comment]
aws should respond something like 200 /index.html for resources that it didn't find. in this case Angular app will be loaded, and it will hadle 'FE paths' inside of itself

**Pull request merged**
